[package]
name = "subsonic_vault"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
crossbeam = "0.8.4"
env_logger = "0.11.8"
md-5 = "0.10.6"
rand = "0.9.2"
serde = "1.0.228"
serde_json = "1.0.145"
